import { nanoid } from 'nanoid'
import { db, type Contact } from './db'

const now = Date.now()
const day = 86400000

const sampleContacts: Omit<Contact, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    firstName: 'Priya',
    lastName: 'Sharma',
    company: 'Stripe',
    title: 'Senior Engineer',
    phone: '(415) 555-0142',
    email: 'priya.sharma@stripe.com',
    city: 'San Francisco',
    state: 'CA',
    country: 'US',
    linkedin: 'priyasharma',
    twitter: 'priya_codes',
    website: '',
    tags: ['engineering', 'fintech', 'mentor'],
    howWeMet: 'Spoke at a payments meetup in SF, Nov 2024',
    notes: 'Super sharp on distributed systems. Offered to intro me to their hiring manager.',
    favorite: 1,
    lastContacted: now - 3 * day,
    relationshipStrength: 4,
  },
  {
    firstName: 'Marcus',
    lastName: 'Chen',
    company: 'Andreessen Horowitz',
    title: 'Partner',
    phone: '(650) 555-0198',
    email: 'marcus@a16z.com',
    city: 'Menlo Park',
    state: 'CA',
    country: 'US',
    linkedin: 'marcuschen',
    twitter: '',
    website: 'https://marcuschen.com',
    tags: ['investor', 'vc', 'crypto'],
    howWeMet: 'Intro from Priya at a16z office hours',
    notes: 'Interested in developer tools and infra. Prefers warm intros. Follows up fast.',
    favorite: 1,
    lastContacted: now - 14 * day,
    relationshipStrength: 3,
  },
  {
    firstName: 'Sarah',
    lastName: 'Williams',
    company: 'Notion',
    title: 'Head of Product',
    phone: '',
    email: 'sarah.w@notion.so',
    city: 'New York',
    state: 'NY',
    country: 'US',
    linkedin: 'sarahwilliams',
    twitter: 'sarahw_product',
    website: '',
    tags: ['product', 'saas', 'design'],
    howWeMet: 'ProductHunt launch day — she DMed me on Twitter',
    notes: 'Great product thinker. Helped me refine our onboarding flow.',
    favorite: 0,
    lastContacted: now - 30 * day,
    relationshipStrength: 3,
  },
  {
    firstName: 'James',
    lastName: 'Okonkwo',
    company: 'Figma',
    title: 'Staff Designer',
    phone: '(212) 555-0177',
    email: 'james.o@figma.com',
    city: 'Brooklyn',
    state: 'NY',
    country: 'US',
    linkedin: 'jamesokonkwo',
    twitter: 'james_designs',
    website: 'https://jamesokonkwo.design',
    tags: ['design', 'ui', 'friend'],
    howWeMet: 'Design conference in Brooklyn, summer 2024',
    notes: 'Incredibly talented. Freelances on the side for select projects.',
    favorite: 0,
    lastContacted: now - 7 * day,
    relationshipStrength: 4,
  },
  {
    firstName: 'Elena',
    lastName: 'Rodriguez',
    company: 'Datadog',
    title: 'Engineering Manager',
    phone: '(512) 555-0133',
    email: 'elena.r@datadoghq.com',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    linkedin: 'elenarodriguez',
    twitter: '',
    website: '',
    tags: ['engineering', 'leadership', 'observability'],
    howWeMet: 'KubeCon 2024, chatted at the Datadog booth',
    notes: 'Building out their real-time alerting team. Looking for senior engineers.',
    favorite: 0,
    lastContacted: now - 45 * day,
    relationshipStrength: 2,
  },
  {
    firstName: 'Alex',
    lastName: 'Kim',
    company: 'Vercel',
    title: 'Developer Advocate',
    phone: '',
    email: 'alex@vercel.com',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    linkedin: 'alexkim',
    twitter: 'alexkim_dev',
    website: 'https://alexkim.dev',
    tags: ['devtools', 'frontend', 'content'],
    howWeMet: 'He reviewed my open source PR on Next.js',
    notes: 'Super helpful and responsive. Great for getting early access to Vercel features.',
    favorite: 1,
    lastContacted: now - 5 * day,
    relationshipStrength: 5,
  },
  {
    firstName: 'Nina',
    lastName: 'Patel',
    company: 'Goldman Sachs',
    title: 'VP, Technology',
    phone: '(212) 555-0201',
    email: 'nina.patel@gs.com',
    city: 'New York',
    state: 'NY',
    country: 'US',
    linkedin: 'ninapatel',
    twitter: '',
    website: '',
    tags: ['finance', 'engineering', 'enterprise'],
    howWeMet: 'College friend, stayed in touch over the years',
    notes: 'Moved from SWE to management track. Good perspective on enterprise sales.',
    favorite: 0,
    lastContacted: now - 60 * day,
    relationshipStrength: 4,
  },
  {
    firstName: 'Tom',
    lastName: 'Bradley',
    company: '',
    title: 'Freelance Consultant',
    phone: '(303) 555-0156',
    email: 'tom@tombradley.co',
    city: 'Denver',
    state: 'CO',
    country: 'US',
    linkedin: 'tombradley',
    twitter: 'tom_consults',
    website: 'https://tombradley.co',
    tags: ['consultant', 'strategy', 'startup'],
    howWeMet: 'Mutual friend intro at a Denver startup event',
    notes: 'Helps early-stage startups with go-to-market strategy. Reasonable rates.',
    favorite: 0,
    lastContacted: null,
    relationshipStrength: 2,
  },
]

export async function seedDatabase() {
  const count = await db.contacts.count()
  if (count > 0) return

  const contacts: Contact[] = sampleContacts.map((c, i) => ({
    ...c,
    id: nanoid(),
    createdAt: now - (sampleContacts.length - i) * day,
    updatedAt: now - (sampleContacts.length - i) * day,
  }))

  await db.contacts.bulkAdd(contacts)
}
